version: "3.7"
services: 
    proxy:
        image: nginx:alpine
        container_name: proxy
        volumes:
            - ./etc/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./etc/ssl:/etc/ssl/private:ro            
            - ./etc/self-signed.conf:/etc/nginx/conf.d/self-signed.conf:ro            
            - ./etc/ssl-params.conf:/etc/nginx/conf.d/ssl-params.conf:ro            
            - ./entrypoint/proxy:/docker-entrypoint.d:ro
            - ./log:/var/log/nginx:rw
        networks:
            - app-network
            - app-internal
        ports:
            - 80:80
            - 443:443
        depends_on:
            - site
            - cdn
        links: 
            - site
            - cdn
        restart: always

    cdn:
        image: nginx:alpine
        container_name: cdn
        volumes:
            - ./etc/nginx-cdn.conf:/etc/nginx/conf.d/default.conf:ro
            - ./entrypoint/cdn:/docker-entrypoint.d:ro
            - ./cdn:/var/www/html:ro
            - ./log:/var/log/nginx:rw
        networks: 
            - app-internal
        ports:
            - 80:80
        restart: always

    site:
        image: nginx:alpine
        container_name: site
        volumes:
            - ./etc/nginx-site.conf:/etc/nginx/conf.d/default.conf:ro            
            - ./entrypoint/site:/docker-entrypoint.d:ro
            - ./log:/var/log/nginx:rw
            - ./site:/var/www:ro
        networks:
            - app-internal
        ports:
            - 80:80
        restart: always

networks:
    app-network:
        driver: bridge
        internal: false
        
    app-internal:
        driver: bridge
        internal: true        